// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqQjMTahtw9ApHaEPhTFEfHyDGUgnS0PE',
    appId: '1:767702783174:web:ceabe2bb00a1f9f8b0f3c7',
    messagingSenderId: '767702783174',
    projectId: 'firegram-67fe8',
    authDomain: 'firegram-67fe8.firebaseapp.com',
    storageBucket: 'firegram-67fe8.firebasestorage.app',
    measurementId: 'G-84CKCRFE4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0msfBodwzE5uhH-8lc8nJYrrAhQEB7U',
    appId: '1:767702783174:android:257ce46aa272bf4ab0f3c7',
    messagingSenderId: '767702783174',
    projectId: 'firegram-67fe8',
    storageBucket: 'firegram-67fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaO-FAgdKjdTmGbeqclEPiw_G0YWErTGU',
    appId: '1:767702783174:ios:5945b6daf27db71ab0f3c7',
    messagingSenderId: '767702783174',
    projectId: 'firegram-67fe8',
    storageBucket: 'firegram-67fe8.firebasestorage.app',
    iosBundleId: 'com.firegram.app.firegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaO-FAgdKjdTmGbeqclEPiw_G0YWErTGU',
    appId: '1:767702783174:ios:5945b6daf27db71ab0f3c7',
    messagingSenderId: '767702783174',
    projectId: 'firegram-67fe8',
    storageBucket: 'firegram-67fe8.firebasestorage.app',
    iosBundleId: 'com.firegram.app.firegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqQjMTahtw9ApHaEPhTFEfHyDGUgnS0PE',
    appId: '1:767702783174:web:56543b887b2d8fcdb0f3c7',
    messagingSenderId: '767702783174',
    projectId: 'firegram-67fe8',
    authDomain: 'firegram-67fe8.firebaseapp.com',
    storageBucket: 'firegram-67fe8.firebasestorage.app',
    measurementId: 'G-FJXWV8F11L',
  );
}
